### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by mehrdad-shokri** [Kysic/webdavFileTree#2]
How to insltall and utilize this lib?

**Comment by Kysic** [comment]
Hi Mehrdaad,

You would have to adapt to your need, but here how I use it.
I have a front http server that is exposed to the internet.
This server host the webdavFileTree pages and is also used as a proxy to my webdav NAS that is not accessible from the internet.
More specifically, the code from this project is in a "/var/www/webdavfiletree" directory of my http server, and the http server contains the following configuration lines:
```
<VirtualHost _default_:443>
  ServerName webdavfiletree.example.com
  DocumentRoot /var/www/webdavfiletree
  SSLCertificateFile  /etc/letsencrypt/live/webdavfiletree.example.com/fullchain.pem 
  SSLCertificateKeyFile   /etc/letsencrypt/live/webdavfiletree.example.com/privkey.pem 
  ProxyPreserveHost On
  ProxyPass "/webdav/" "https://192.168.7.250/webdav/"
  ProxyPassReverse "/webdav/" "https://192.168.7.250/webdav/"
  SSLProxyEngine On
  SSLProxyVerify none 
  SSLProxyCheckPeerCN off
  SSLProxyCheckPeerName off
  SSLProxyCheckPeerExpire off
</VirtualHost>
```
where 192.168.7.250 is the IP of my NAS on my private network.
Some SSL security option are disabled because my NAS uses an auto-generated SSL certificate, but is just options used for the communication between the http server and the NAS (so on private network), between the http server and the client http browser the communication is secure with a legitimate certificate (thanks to letsencrypt).
